### ISSUE TITLE
gbrs_emissions_all_tissues.avecs.npz  python error 

### ISSUE THREAD

**Issue by lawtyunc** [TheJacksonLaboratory/cs-nf-pipelines#14]
Hello all,

 I am currently trouble shooting and trying to get the gbrs_emissions_all_tissues.avecs.npz script to work but I am running into a few errors that I believe may be related to my meta file? 

Found the following sample counts matched to sample IDs in the input directory...
**0 comes up he**re 

dset[st] = dmat_strain / len(dlist[st])
Confirming we have TPM for all found genes and strains...
ValueError: cannot convert float NaN to integer

I think it has something to do with dividing by zero but I think it might have something to do with the format of my metadata.csv but still not entirely sure?

**Comment by MikeWLloyd** [comment]
The script is failing because it has not found EMASE output in the input directory provided to the script. Can you provide the full command you are running, and the full contents of your metadata file?

**Comment by lawtyunc** [comment]
python3 generate_emission_prob_avecs.py 
-i path_to/emase/ 
-o path_to_output/ 
-g path_to/emase.gene2transcripts.tsv 
-m path_to/meta.table.csv
 I tried this 2 different ways because I was trying to follow the arguments from the script  that was on github but both options ended up failing for some reason

    do_id, sampleID      
    A      Sample1
    B      Sample1
    C      Sample1


sampleID,tissue,strain,DO_id,sex,exclude
129_1_Adipose,Adipose,129S1_SvImJ,C,F,NO

**Comment by lawtyunc** [comment]
in this path_to/emase/ there is 

multiway.genes.tpm
and other emase output files 
 
I am currently testing this for one sample

**Comment by MikeWLloyd** [comment]
You created a directory named `path_to`? That name was only intended for demonstration. 

Working example command:
``` 
python /projects/cs-nf-pipelines/bin/generate_emission_prob_avecs.py \
--input_directory /projects/results/liver/ \
--output_directory /projects/results/emission_probabilities/ \
--output_prefix gbrs_emissions_liver \
-g /projects/eight_way_transcriptome/emase/emase.gene2transcripts.tsv \
--metadata_file /projects/raw_founder_rnaseq_fastq/GBRS_CleanMetadata.csv
```

Where input_directory is the full EMASE results directory with samples organized into sub-directories. The output from the emase workflow is expected. 

Here is what I mean by the output directories from EMASE
```
ls -1 /projects/results/liver
10146_GES11_4343_CGATGT_L007_R1_ALL
10176_GES11_4348_CTTGTA_L004_R1_ALL
...
```

And what is expected inside each, which again come directly from the workflow: 

```
ls -1 /projects/results/liver/10146_GES11_4343_CGATGT_L007_R1_ALL/*

/projects/results/liver/10146_GES11_4343_CGATGT_L007_R1_ALL/emase:
10146_GES11_4343_CGATGT_L007_R1_ALL.compressed.emase.h5
10146_GES11_4343_CGATGT_L007_R1_ALL.multiway.genes.alignment_counts
10146_GES11_4343_CGATGT_L007_R1_ALL.multiway.genes.expected_read_counts
10146_GES11_4343_CGATGT_L007_R1_ALL.multiway.genes.tpm
10146_GES11_4343_CGATGT_L007_R1_ALL.multiway.isoforms.alignment_counts
10146_GES11_4343_CGATGT_L007_R1_ALL.multiway.isoforms.expected_read_counts
10146_GES11_4343_CGATGT_L007_R1_ALL.multiway.isoforms.tpm

/projects/results/liver/10146_GES11_4343_CGATGT_L007_R1_ALL/stats:
10146_GES11_4343_CGATGT_L007_R1_ALL.bowtie_R1.log
```



The sampleID provided in the metadata file, must match the sampleIDs that are output from the EMASE workflow. 
```
sampleID,tissue,strain,hap_id,sex,exclude
10146_GES11_4343_CGATGT_L007_R1_ALL,Liver_Svenson,NOD_ShiLtJ,D,NA,NO
10176_GES11_4348_CTTGTA_L004_R1_ALL,Liver_Svenson,NOD_ShiLtJ,D,NA,NO
...
```

Note, we have updated the script in the latest release to use the header `hap_id` rather than `do_id`, and to make the script flexible with respect with number of strains. Ensure you are using the most recent version.

**Comment by lawtyunc** [comment]
So I updated to the new version of the script by redownloading it from github so that it says hap_id and then I also updated my metadata file to reflect what you showed above but for some reason, I am still getting the same error. I am only testing this with one sample to start out

**Comment by lawtyunc** [comment]
Do you have to remove zeros or anything from the matrix?

**Comment by MikeWLloyd** [comment]
If all inputs are name matched, I suspect a single sample is insufficient. No modification of the count matrices are required. Try running more samples.

**Comment by lawtyunc** [comment]
Hey Mike, 
So I actually got the python script to work and run through with no errors!! Thank you for your help on this. Is there an easy way to check if the results are what are expected from the npz output?
